import express from "express";
import qualificationCtrl from "../controllers/education.controller.js";
const router = express.Router();
router.route("/api/qualifications").post(qualificationCtrl.create);
router.route("/api/qualifications").get(qualificationCtrl.list);
router.param("educationId", qualificationCtrl.educationByID);
router.route("/api/qualifications/:educationId").get(qualificationCtrl.read);
router.route("/api/qualifications/:educationId").put(qualificationCtrl.update);
router.route("/api/qualifications/:educationId").delete(qualificationCtrl.remove);
export default router;